android/src/playn/android/AndroidAssets.java
android/src/playn/android/AndroidGraphics.java
android/src/playn/android/AndroidPlatform.java
android/src/playn/android/GameViewGL.java
core/src/playn/core/Graphics.java
html/src/playn/html/HtmlGraphics.java
java-base/src/playn/java/JavaAssets.java
java-base/src/playn/java/JavaGraphics.java
java-base/src/playn/java/JavaPlatform.java
java-lwjgl/src/playn/java/LWJGLGraphics.java
java-swt/src/playn/java/SWTGraphics.java
robovm/src/playn/robovm/RoboGraphics.java
robovm/src/playn/robovm/RoboPlatform.java

We're working a project in which we need to replay the game and record it into video on every platform, in which case, it's really not necessary to load the whole platform and Graphics is good enough. In addition, the graphic related configuration is all platform specific graphics need.
This commit will cause code breaks for registering additional fonts on specific platforms. Those can be easily fixed by calling the plat.assets().getFont() or equivalent methods on specific platforms.

Decouple platform-related stuff from Graphics

---

core/src/playn/core/Texture.java

An obvious error that causes sub-region rendering to fail in most cases.

texture rendering coordinate fix

---

html/src/playn/html/HtmlInput.java
html/src/playn/html/HtmlPlatform.java

Hi @samskivert 
Here is the UserAgent info from the different windows browsers
```
Edge:   Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240"
IE11:   mozilla/5.0 (windows nt 6.1; wow64; trident/7.0; slcc2; .net clr 2.0.50727; .net clr 3.5.30729; .net clr 3.0.30729; media center pc 6.0; .net4.0c; .net4.0e; rv:11.0) like gecko
Chrome: mozilla/5.0 (windows nt 6.1; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/48.0.2564.97 safari/537.36
```
<code>HtmlInput</code> accepts Edge and Chrome as Chrome and IE11 as unknown browser. Therefore WheelVelocity sets to zero.
This PR fixes this

IE11 mouseWheel fixed

---

core/src/playn/core/Surface.java

Don't flip Y coordinate when the backbuffer doesn't require flipping.

fix scissor coordinate calculation

---

core/src/playn/core/Surface.java

Use an early test to determine if a quad will actually fall inside our rendering area. Although the GPU is quick to discard these quads, this is still useful because invalid data won't pollute the UniformQuadBatch buffer and thus reduce the number of draw calls and data copied to the GPU.

Don't submit quads to the GPU if they won't be drawn

---

html/src/playn/html/HtmlGL20.java

This is what libgdx does and it seems more efficient and less "over-engineered" than the unified map.

gwt gl20 sync: Use one map per object type instead of a big unified map

---

html/src/playn/html/HtmlImage.java

Call the base class succeed/fail functions on load/error event. 
The reasons for this changes are:  when an image fails to load, then the error image doesn't set (only the status has been changed)

Html image load fix

---

pom.xml

See #54 
Passing `--release 8` to javac works.
However java 8 will complain if it sees this new flag, thus I added a java 9 maven profile.

Make JDK9 produce Java 8 compatible bytecode

---

core/src/playn/core/Image.java

This disposes the image's default texture if it has been already
created, and does nothing otherwise.

Add new Image.close() method.

---

scene/src/playn/scene/ClippedLayer.java

This handles the case where the layer is rotated a multiple of 90
degrees by normalizing the clipping rectangle so that both width
and height are always >0.

Fix handling of negative sizes of the clipping rectangle.

---

android/src/playn/android/AndroidStorage.java

apply() is faster (commits changes asynchronously), and available
from API level 9. Replacing commit() with apply() is safe in all
cases where the return value from commit() was already being ignored.
Ref: https://developer.android.com/reference/android/content/SharedPreferences.Editor#apply()

Replace calls to SharedPreferences.commit() with .apply()

---

core/src/playn/core/Scale.java

This rounds the supplied length to the nearest value
that corresponds to an integer length after scaling.
See https://facebook.github.io/react-native/docs/pixelratio
for a rationale.

Added roundToNearestPixel.

---

scene/src/playn/scene/ImageLayer.java

In the case where the new tile is a subregion of the previous tile's texture, the texture is closed by de-referencing.

reference texture before release previous (can be the same)

---

android/src/playn/android/AndroidInput.java

On some android devices a call to getText shows the EditText but doesn't automatically show the soft keyboard, hence the user must touch the textfield once for it to show up. This PR makes it so that the keyboard is shown directly

show soft keyboard automatically on getText

---

android/src/playn/android/AndroidInput.java
core/src/playn/core/Input.java
html/src/playn/html/HtmlInput.java
java-lwjgl/src/playn/java/GLFWInput.java
java-lwjgl2/src/playn/java/LWJGLInput.java
java-swt/src/playn/java/SWTInput.java
robovm/src/playn/robovm/RoboInput.java

I noticed that getText had hardcoded "Ok" and "Cancel" as labels for the buttons (like sysDialog does). This PR fixes it, while being backwards compatible with those labels as defaults

enable passing labels for "ok" and "cancel" labels in getText

---

robovm/src/playn/robovm/RoboPlatform.java

The current code ends up calling the native `timerWithTimeInterval:target:selector:userInfo:repeats:` method. This creates the timer but does not start it (it does not add it to a run loop).
With this commit, the `scheduledTimerWithTimeInterval:target:selector:userInfo:repeats:` is used instead, which creates *and* schedules the timer.

NSTimer created in RoboPlatform.willTerminate would never fire.

---

robovm/src/playn/robovm/RoboPlatform.java

Not shutting down the thread pool was preventing the
RoboPlatform from being GC'ed when not in use anymore.

Fix memory leak.

---

robovm/src/playn/robovm/RoboGraphics.java

Starting with iOS 8.0, UIScreen.nativeScale should be used to convert
from points to physical device pixels. In many cases, the "native scale"
and "scale" values match, but there are some exceptions:
- Devices that perform hardware downsampling (iPhone 6+/6s+/7+/8+)
- Devices supporting zoomed display mode (all iPhone 6/7/8 variants),
when display mode is enabled.
This fixes #78.

Use UIScreen.nativeScale instead of scale where available (iOS 8+)

---

java-swt/pom.xml

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …

[SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

android/src/playn/android/AndroidCanvas.java

There is a problem in AndroidCanvas.fillRoundRect() related to gradient fills.
Here's a test that fills some round rects using a linear gradient:
Linear config = new Linear(0, 0, width, 0,
new int[] { 0xffff0000, 0xff00ff00, 0xff0000ff },
new float[] { 0f, 0.5f, 1f });
Gradient gradient = canvas.createGradient(config);
canvas.setFillGradient(gradient);
canvas.fillRoundRect(0, 120, width, 50, 5);
canvas.fillRoundRect(0, 180, width / 2 - 5, 50, 5);
canvas.fillRoundRect(width / 2 + 5, 180, width / 2 - 5, 50, 5);
This is how it should look like:
This is how it looks like in Android:
The problem is that the origin for the gradient fill is reset to the origin of each shape (see the rectangle in the bottom right).
This seems to be due to the [current implementation of …

Fix rendering issue in fillRoundRect/strokeRoundRect

---

robovm/src/playn/robovm/RoboCanvas.java

Some methods were missing calls to save/restore state when used with gradients. The clip was being modified internally and resulting in incorrect results for subsequent drawing operations.

Canvas: add some missing calls to save/restore state

---

core/src/playn/core/Image.java

Regions were caching tile instances which may refer to textures that
may already have been disposed. Now this is detected when tile()
is called and a new tile is created from the new texture.

Regenerate region tiles from disposed textures

---

android/src/playn/android/AndroidTextLayout.java

Set the LINEAR_TEXT_FLAG to fix text rendering when using non-integer font sizes. Without this, the extent of text runs for non-integer font sizes seems to be calculated based on integer sizes, and the letter spacing seems to be wrong.
After this change, the rendering of text in Android is much closer to the results when using PlayN on robovm/iOS.
Before the change:
Notice how the glyphs of the 12.5 font are noticeable larger than the ones of the 12 font, but the line width is the same.
After the change:
(Tests made in Android 10)

Fix text rendering for non-integer font sizes

---

scene/src/playn/scene/SceneGame.java

Modify SceneGame.paintScene to avoid calling saveTx/restoreTx internally. Since this may be executed 30-60 times per second, it's nice if we can avoid generating garbage.

Avoid saveTx/restoreTx calls for GC-friendliness

---

core/src/playn/core/Surface.java

The initial transform was being pushed onto the transformStack, which was always unbalanced. This should not be needed.

Surface: Do not push initial transform onto the stack

---

.github/workflows/build.yml

This adds a GitHub action that runs a build (along with all tests) on every PR that is created or updated.
PRs won't be mergeable if the build fails (unless the action is overriden).

Add GH action to run a build on every PR

---

html/src/playn/html/HtmlGraphics.java
html/src/playn/html/HtmlPlatform.java

For the html background, this change allows configuring the width/height of the root element in the HtmlPlatform.Config object. If both width and height are non-zero, then these are configured in the root node as inline styles. If any of the two is 0 (the default) the current behaviour is kept.
I believe that for simple use cases this is slightly more developer-friendly than having to customize the default index.html page. Also it is consistent with the width/height options in the Java backend.

html: Support setting width/height in Config object

---

core/src/playn/core/Surface.java

This adds a method to draw the outline of a rectangle, with the specified line width. This is implemented internally as a set of 4 calls to drawLine.
I know that the Surface API should be kept as simple as possible and map to accelerated GPU primitives but it feels strange to have a fillRect method and not a corresponding drawRect. Also the implementation is simple enough so I think it's worth adding this.

Surface: Add drawRect method

---

core/src/playn/core/Graphics.java
core/src/playn/core/TextLayout.java

This avoids inconsistencies in handling of leading/trailing whitespace when measuring text on different platforms.

Trim whitespace from text in TextLayout.
